#!/usr/bin/env sh

### DEPENDENCIES ###
pytool() {
    SCRIPT=$1; shift
    python3 ~/code/py/tool/$SCRIPT.py "$@"
}


### ALIASES COMMANDS ###
alias nv="nvim"
alias nvzc="nv $HOME/.zshrc"
alias nvac="nv $HOME/.config/aliases"
alias nvhc="nv $HOME/.zsh_history"
alias nvtc="nv $HOME/.tmux.conf"
alias nvnc="nv $HOME/.config/nvim/init.vim"
alias nvgs="nv -c ':Gs'"
alias nvcg="nv $HOME/.config/startup"
alias srczsh="source $HOME/.zshrc"
alias tl="tmux ls"
alias ta="tmux attach -t"
alias td="tmux detach"
alias tk="tmux kill-session -t"
alias clc="clear && printf '\033[3J'"
alias exa="exa --group-directories-first"
alias l="pytool myls"
alias ls="exa --group-directories-first"
alias ll="ls -alh --git"
alias c="clear; ls"
alias ..="cd .."
alias ...="cd ../.."
alias rm="rm -ri"
alias mv="mv -i"
alias cp="cp -ri"
alias xclip="xclip -selection c -r"
alias tcopy="tmux show-buffer | xclip"
alias cpwd="pwd | xclip"
alias :q="exit"
alias dodo="systemctl suspend"
alias py="python3"
alias pip="py -m pip"
alias delta="$HOME/sw/delta"
alias dust="dust -r -d 1"
alias fd="fdfind"
alias equation-latex="nv $HOME/code/tex/quick-equation/main.tex"
alias tmuxify-command="nv $HOME/.config/nvim/tmuxify_command.sh"
alias du="du -h"
alias disk="df -hx'squashfs'"
alias startup="$HOME/.config/startup"
alias update="sudo apt update && sudo apt upgrade -y"
alias record="arecord -f cd"
alias git_modif_date="git ls-files -z | xargs -0 -n1 -I{} -- git log -1 --format=\"%ai {}\" {} | sort"


### FUNCTIONS COMMANDS ###
cd() {
    builtin cd "$@" && ls
    if [ -z "$@" ]; then
        c
    fi
}
do_exist() {
    [[ -f "$1" ]] || echo "cannot open $1"
}
pdf() {
    for file in "$@"; do
        $(do_exist "$file") && xdg-open "$file" &>/dev/null
    done
}
mdiff() {
    diff -u $1 $2 | delta
}
path() {
	old=$IFS
	IFS=:
	printf "%s\n" $PATH
	IFS=$old
}
copy() {
    echo "$@" | xclip
}
fcopy() {
    cat "$@" | xclip
}
fsync() {
    cp "$@" ~/doc/sync/default
}
tm() {
    [[ $# -eq 0 ]] && SESSION="main" || SESSION="$1"
    # Complex sessions
    if [[ $SESSION == "obs" ]]; then
        tmux new-session -s $SESSION -n "main" -c "$HOME/obs/ts" \; \
             send-keys 'c' C-m \; \
             split-window -hc "$HOME/obs/ts/doc" \; \
             new-window -n "A11" -c "$HOME/obs/rf_bench_a11"\; \
             send-keys 'c' C-m \; \
             attach
    elif [[ $SESSION == "main" ]]; then
        tmux new-session -s $SESSION -n "" -c "$HOME" \; \
             new-window -n "main" -c "$HOME"\; \
             attach
    elif [[ $SESSION == "rob" ]]; then
        tmux new-session -s $SESSION -n "main" -c "$HOME/rob" \; \
             split-window -vc "$HOME/rob" \; \
             send-keys 'nv todo.md notes.md' C-m \; \
             new-window -n "doc" -c "$HOME/rob/doc"\; \
             split-window -vc "$HOME/rob/doc/ref" \; \
             split-window -hc "$HOME/doc/nextcloud/kalast/doc" \; \
             new-window -n "kalast" -c "$HOME/rob/code/kalast"\; \
             select-window -t 1 \; \
             attach
    # Simple sessions
    else
        declare -A sessions=( ["other"]="." )
        tmux new-session -s $SESSION -n "main" -c "$HOME/${sessions[$SESSION]}"
    fi
}
silent() {
    "$@" &>/dev/null &
}
space-remove() {
    for file in *; do mv "$file" `echo $file | tr ' ' '_'` ; done
}

### ALIASES APPLICATIONS ###
alias matlab="$HOME/sw/matlab/bin/matlab"
alias julia="$HOME/sw/julia-1.5.3/bin/julia"
alias mat='matlab -nodesktop'
alias oct='octave --no-gui'
alias vts='~/sw/vts/startVTS'
alias web='firefox'
alias telegram='~/sw/Telegram/Telegram 2>/dev/null &'
alias inkscape='silent flatpak run org.inkscape.Inkscape'
alias timidity='~/sw/timidity/script/timidity'
alias ffplay='ffplay -vf "drawtext=text='\''%{pts\:hms}'\'':box=1:x=(w-tw)/2:y=h-(2*lh)"'
alias vlc='flatpak run org.videolan.VLC &>/dev/null'
alias krita='silent flatpak run org.kde.krita'
alias xournal='flatpak run com.github.xournalpp.xournalpp &>/dev/null'
alias gimp='flatpak run org.gimp.GIMP'
alias okular='flatpak run org.kde.okular &>/dev/null'
alias piksel='/home/grhenry/sw/piskel/piksel'
alias foxit='/home/grhenry/sw/foxit/foxitsoftware/foxitreader/FoxitReader.sh 2>/dev/null &'
alias zoom='silent flatpak run us.zoom.Zoom'
alias vscode='silent flatpak run com.vscodium.codium'
alias slack='silent flatpak run com.slack.Slack'
alias telegram='silent flatpak run org.telegram.desktop'
alias discord='silent flatpak run com.discordapp.Discord'
alias skype='silent flatpak run com.skype.Client'
alias syncthing="silent flatpak run me.kozec.syncthingtk"
alias vpn-rob="sudo openvpn --config $HOME/doc/vpn/gregoireh.ovpn"
alias mellow="silent flatpak run com.gitlab.ColinDuquesnoy.MellowPlayer"
alias meshlab="silent $HOME/sw/meshlab.appimage"
alias teams="silent flatpak run com.microsoft.Teams"
alias nextcloud="silent flatpak run com.nextcloud.desktopclient.nextcloud"
alias glade="silent flatpak run org.gnome.Glade"
alias mattermost="silent flatpak run com.mattermost.Desktop"
alias cosmographia="silent $HOME/sw/cosmographia/Cosmographia.sh"
