#!/usr/bin/env sh

# Detect key press faster and repeat them faster.
# Values are given in ms: delay and rate (default: 660 25).
xset r rate 190 60

# Remap Caps Lock to Ctrl key.
setxkbmap -option 'caps:ctrl_modifier'

# When no key associated with Caps Lock within 1s, it is considered as Escape.
xcape -e 'Caps_Lock=Escape' -t 1000 &
